// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://alkjgogriwshdpkuwqhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsa2pnb2dyaXdzaGRwa3V3cWhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNjMxNTgsImV4cCI6MjA2MjYzOTE1OH0.r5L_szYXfqtnW5qwgMaITQp-pT5KGiteQfaUxGFgkJs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);